name: flutter_dropzone_example
description: Demonstrates how to use the flutter_dropzone plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_dropzone: ^3.0.4
  flutter_lints: ^2.0.0

dev_dependency_overrides:
  flutter_dropzone:
    git:
      url: https://github.com/Supernova-Studio/flutter_dropzone.git
      path: flutter_dropzone
  flutter_dropzone_platform_interface:
    git:
      url: https://github.com/Supernova-Studio/flutter_dropzone.git
      path: flutter_dropzone_platform_interface
  flutter_dropzone_web:
    git:
      url: https://github.com/Supernova-Studio/flutter_dropzone.git
      path: flutter_dropzone_web

flutter:
  uses-material-design: true
