name: flutter_dropzone
description: A drag-and-drop Flutter plugin (Web only).
version: 2.0.1
homepage: https://github.com/deakjahn/flutter_dropzone

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dropzone_platform_interface:
    path: ../flutter_dropzone_platform_interface
  flutter_dropzone_web:
    path: ../flutter_dropzone_web

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        default_package: flutter_dropzone_web
